### PR TITLE
Update pyproject.toml - urllib3>=1.25,<=2.1.0

### PR DESCRIPTION
**Pull request by yyolk**
restrict 2.2.0 urllib3 for mypy errors during gh-actions

[2.2.0 was released](https://github.com/urllib3/urllib3/releases/tag/2.2.0) 3 days ago and I think that's the cause of the failed builds

Apologies if I missed something during this drive-by PR, I was evaluating Dulwich and saw the build errors, and wanted to know why it was failing and I think this is the root cause.

### CODE REVIEW

**Review by jelmer — APPROVED** [review]

**Comment by yyolk** [comment]
I think there's probably more to it. Upon comparing [2.2.0 vs 2.1.0](https://github.com/urllib3/urllib3/compare/2.1.0...2.2.0)

I'll close this PR since it should be fine to use the latest urllib3 as it is. Apologies for the noise.

**Comment by yyolk** [comment]
I also thought mypy may have been updated, but it was the same 1.8.0 version in the last successful scheduled build with ubuntu @ python3.12 and python3.11 (which I guess the workflow regressed between these two master branch builds)

I was being lazy and didn't test running the actions myself 😅 

**Success [1246](https://github.com/jelmer/dulwich/actions/runs/7676824869/job/20924835010) (python 3.12)** `mypy-1.8.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64`
image

**Failed [1254](https://github.com/jelmer/dulwich/actions/runs/7683861547/job/20939696835) (python 3.11)** `mypy-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64`
image

**Comment by yyolk** [comment]
for posterity, I did end up running mypy. 

Sorry for the noise, hopefully it's helpful in the future


```sh
% python -m mypy dulwich
dulwich/graph.py:46: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
dulwich/contrib/paramiko_vendor.py:33: error: Library stubs not installed for "paramiko"  [import-untyped]
dulwich/contrib/paramiko_vendor.py:34: error: Library stubs not installed for "paramiko.client"  [import-untyped]
dulwich/contrib/paramiko_vendor.py:34: note: Hint: "python3 -m pip install types-paramiko"
dulwich/contrib/paramiko_vendor.py:34: note: (or run "mypy --install-types" to install all missing stub packages)
dulwich/contrib/paramiko_vendor.py:34: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
dulwich/objects.py:1199: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
dulwich/diff_tree.py:267: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
dulwich/diff_tree.py:314: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
dulwich/server.py:1113: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
dulwich/client.py:2213: error: "Mapping[str, str]" has no attribute "update"  [attr-defined]
dulwich/contrib/requests_vendor.py:34: error: Library stubs not installed for "requests"  [import-untyped]
dulwich/contrib/requests_vendor.py:34: note: Hint: "python3 -m pip install types-requests"
dulwich/contrib/test_paramiko_vendor.py:30: error: Library stubs not installed for "paramiko"  [import-untyped]
dulwich/contrib/test_paramiko_vendor.py:131: error: Library stubs not installed for "paramiko.transport"  [import-untyped]
Found 6 errors in 4 files (checked 97 source files)
% pip freeze
-e git+ssh://git@github.com/yyolk/dulwich@98f303bdb24bd31ec25a543f7ab7af1d6704fa8f#egg=dulwich
flake8==7.0.0
mccabe==0.7.0
mypy==1.8.0
mypy-extensions==1.0.0
pycodestyle==2.11.1
pyflakes==3.2.0
typing_extensions==4.9.0
urllib3==2.1.0
```

**Comment by jelmer** [comment]
No worries - thanks for the detailed follow-up!
