### ISSUE TITLE
Breaking change in 0.24.2

### ISSUE THREAD

**Issue by aayushchhabra1999** [jelmer/dulwich#1895]
Is the version 0.24.2 stable? We are using Poetry for our production application. Poetry locks to dulwich >=0.24.0,<0.25.0

The tags page shows 0.24.2 as unverified
<img width="1166" height="304" alt="Image" src="https://github.com/user-attachments/assets/787648d1-fe71-43df-ab85-6195a4179428" />

But pypi is still hosting 0.24.2 as the latest
<img width="1176" height="581" alt="Image" src="https://github.com/user-attachments/assets/18434e9d-e3a0-4eb4-84fe-15fe2895d419" />

Getting the traceback:
```python
ImportError

  cannot import name 'FilterContext' from 'dulwich.filters' (/usr/local/lib/python3.11/site-packages/dulwich/filters.py)

  at /usr/local/lib/python3.11/site-packages/dulwich/repo.py:2029 in get_blob_normalizer
      2025│         """
      2026│         return self.get_worktree().set_sparse_checkout_patterns(patterns)
      2027│ 
      2028│     @replace_me(remove_in="0.26.0")
    → 2029│     def set_cone_mode_patterns(self, dirs: Union[list[str], None] = None) -> None:
      2030│         """Write the given cone-mode directory patterns into info/sparse-checkout.
      2031│ 
      2032│         For each directory to include, add an inclusion line that "undoes" the prior
      2033│         ``!/*/`` 'exclude' that re-includes that directory and everything under it.

Cannot install httpx-ws.
```

Can someone please share insights? Please correct me if I am using things incorrectly.

Thanks a ton!

**Comment by jelmer** [comment]
@aayushchhabra1999 

What command are you running that triggers the issue? Can you share the full traceback? poetry doesn't import FilterContext as far as I know.

**Comment by jelmer** [comment]
> [@jelmer](https://github.com/jelmer) I am using the fork of a package inside my pyproject.toml like this:
> 
> [tool.poetry.dependencies]
> httpx-ws = { git = "https://github.com/thekniru/httpx-ws.git", rev = "05c91b286d1d110599c9a42c33ba7616ea1a68bb" }
> And then inside a github action, I am doing:
> 
> python -m pip install --upgrade pip
> pip install poetry
> poetry config virtualenvs.create false
> poetry install
> And then it installs a bunch of packages from pypi but when it tries to install any packages that include a git revision reference (the packages with a `{ git = "...", rev = "..." }`, it breaks with the following traceback:
> 
> ```
> - Installing svcs (24.1.0)
> - Installing testcontainers (4.12.0)
> - Installing httpx-ws (0.6.0 05c91b2)
> 
>   ImportError
> 
>   cannot import name 'FilterContext' from 'dulwich.filters' (/usr/local/lib/python3.11/site-packages/dulwich/filters.py)
> 
>   at /usr/local/lib/python3.11/site-packages/dulwich/repo.py:2029 in get_blob_normalizer
>       2025│         """
>       2026│         return self.get_worktree().set_sparse_checkout_patterns(patterns)
>       2027│ 
>       2028│     @replace_me(remove_in="0.26.0")
>     → 2029│     def set_cone_mode_patterns(self, dirs: Union[list[str], None] = None) -> None:
>       2030│         """Write the given cone-mode directory patterns into info/sparse-checkout.
>       2031│ 
>       2032│         For each directory to include, add an inclusion line that "undoes" the prior
>       2033│         ``!/*/`` 'exclude' that re-includes that directory and everything under it.
> 
> Cannot install httpx-ws.
> 
> Error: Process completed with exit code 1.
> ```

Please share the complete traceback; this one seems completely unrelated to the error you're encountering.

> My best guess is that poetry is using FilterContext when a git revision reference is used.

poetry doesn't reference FilterContext at all; FilterContext wasn't introduced until dulwich 0.24.2. Are you sure you don't just have a broken installation somehow?

Jelmer

**Comment by aayushchhabra1999** [comment]
Can't share the above traceback (which simply lists out all our other dependencies) due to security requirements on our end. Sincere Apologies. We can just close this issue for now since we are able to get it working with 0.24.1

If anyone else encounters this, we can revisit. Otherwise, likely some broken installation on our end.

**Comment by jelmer** [comment]
Ok, thanks.
